language: python

python:
  - "3.8"

jobs:
  include:
    - stage: "Lab 2 build"
      name: "Run tests for Lab 2"
      python: 3.8
      install:
        - cd ./lab_2/
        - pipenv install requests
        - pipenv install ntplib
        - pipenv install pytest
      script: 
        - pipenv run pytest tests/tests.py || true
        - pipenv run python3 app.py || true
    - stage: "Lab 4 build"
      name: "Build Docker images & Home task"
      services:
        - docker
      install:
        - cd ./lab_4/
      script:
        - docker build -f Dockerfile -t seidex/chabak_ik-31:django-travis .
        - docker build -f Dockerfile.mon -t seidex/chabak_ik-31:monitoring-travis .
        - docker images
        - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; docker push seidex/chabak_ik-31:django-travis;  else echo "PR skip deploy"; fi
        - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; docker push seidex/chabak_ik-31:monitoring-travis; else echo "PR skip deploy"; fi
    - stage: "Lab 5 build"
      name: "Build and run Docker images via make"
      services:
        - docker
      install:
        - cd ./lab_5/
        - make app
        - make tests
      script:
        - make run
        - make test-app
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make docker-push
branches:
  only:
    - main